name: harness-example
replicas: 1

schedule: "*/1 * * * *"

cronJobs:
  1: job1
  2: job2
  3: job4

image: <+artifact.image>
dockercfg: <+artifact.imagePullSecret>
createNamespace: true
namespace: <+infra.namespace>

serviceType: LoadBalancer
servicePort: 80
serviceTargetPort: 80

env:
  config:
    key1: value1
  secrets:
    key2: value2
