name: new-app-harness-example
replicas: 6
replicasNew: 4
replicasNewNew: 2

secretName: my-secret

createNamespace: true
namespace: pedro-canary

env:
  secrets:
    username: user
    password: pass
