apiVersion: v1
kind: Secret
metadata:
  name: original-crypto
data:
  username: {{ .Values.env.secrets.username | b64enc }}
  password: {{ .Values.env.secrets.password | b64enc }}
  secret_from_harness: {{ .Values.secret_from_harness | b64enc }}
